In [17]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import joblib

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_absolute_error

In [18]:
df = pd.read_csv("heart (1).csv")
print("Shape:", df.shape)
df.head()

Shape: (303, 15)

,Unnamed: 0,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  303 non-null    int64
 1   age         303 non-null    int64
 2   sex         303 non-null    int64
 3   cp          303 non-null    int64
 4   trestbps    303 non-null    int64
 5   chol        303 non-null    int64
 6   fbs         303 non-null    int64
 7   restecg     303 non-null    int64
 8   thalach     303 non-null    int64
 9   exang       303 non-null    int64
 10  oldpeak     303 non-null    float64
 11  slope       303 non-null    int64
 12  ca          303 non-null    int64
 13  thal        303 non-null    int64
 14  target      303 non-null    int64
dtypes: float64(1), int64(14)
memory usage: 35.6 KB

In [20]:
df.isnull().sum()

Unnamed: 0    0
age           0
sex           0
cp            0
trestbps      0
chol          0
fbs           0
restecg       0
thalach       0
exang         0
oldpeak       0
slope         0
ca            0
thal          0
target        0
dtype: int64

In [21]:

df = df.drop("Unnamed: 0",axis=1)

In [22]:
d = {'cp':"chest_pain_type", 'trestbps':"resting_bp", 'chol':"cholestrol", 'fbs':"fasting_blood_sugar", 'thalach':"max_heart_rate", 'exang':"exer_induced_angina", 'ca':"num_major_vessels"}
df.rename(columns=d,inplace=True)
df.head()

,age,sex,chest_pain_type,resting_bp,cholestrol,fasting_blood_sugar,restecg,max_heart_rate,exer_induced_angina,oldpeak,slope,num_major_vessels,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report

In [24]:
X = df.drop("target",axis=1)
y = df.target

In [25]:
Xtrain,Xtest,ytrain,ytest = train_test_split(X,y,test_size=0.3,random_state=42)

In [26]:
model = LogisticRegression()
model.fit(Xtrain,ytrain)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [27]:
print("Training Eff: ",model.score(Xtrain,ytrain))
print("Testing Eff: ",model.score(Xtest,ytest))

Training Eff:  0.8679245283018868
Testing Eff:  0.8131868131868132

In [28]:
ypred = model.predict(Xtest)
ypred

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1])

In [29]:
confusion_matrix(ytest,ypred)

array([[32,  9],
       [ 8, 42]])

In [30]:

print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.80      0.78      0.79        41
           1       0.82      0.84      0.83        50

    accuracy                           0.81        91
   macro avg       0.81      0.81      0.81        91
weighted avg       0.81      0.81      0.81        91

In [31]:
confusion_matrix(ytest,ypred)

array([[32,  9],
       [ 8, 42]])

In [32]:
df.to_csv("Cleaned_df.csv")

In [33]:
import pickle

In [34]:
with open("Log_reg_model.pkl","wb") as file:
    pickle.dump(model,file)